version: "3.10"

services:
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/.ssl:/etc/nginx/.ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "8443:443"
